import jsPDF from "jspdf";
import QRCode from "qrcode";

interface LearnerData {
  id: string;
  name: string;
  institutions: string;
  currentLevel: string;
  timeline: {
    level: string;
    institution: string;
    period: string;
    status: string;
    result?: string;
  }[];
}

export async function generateEduTrackReport(
  learner: LearnerData,
  baseUrl: string
): Promise<void> {
  const doc = new jsPDF();
  const verifyHash = btoa(learner.id).replace(/[^a-zA-Z0-9]/g, "").slice(0, 16);
  const verifyUrl = `${baseUrl}/verify/${verifyHash}`;

  // Generate QR code as data URL
  const qrDataUrl = await QRCode.toDataURL(verifyUrl, {
    width: 120,
    margin: 1,
    color: { dark: "#0F2B46", light: "#FFFFFF" },
  });

  // Header
  doc.setFillColor(15, 43, 70); // primary
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("EduTrack Uganda", 20, 18);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Verified Academic Report", 20, 26);
  doc.setFontSize(8);
  doc.text("Ministry of Education & Sports — Verified Platform", 20, 33);

  // QR Code (top right)
  doc.addImage(qrDataUrl, "PNG", 155, 5, 30, 30);

  // Learner Info
  doc.setTextColor(15, 43, 70);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Learner Information", 20, 55);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);

  const info = [
    ["EduTrack ID", learner.id],
    ["Full Name", learner.name],
    ["Institutions", learner.institutions],
    ["Current Level", learner.currentLevel],
  ];

  let y = 65;
  info.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120, 120, 120);
    doc.text(label, 20, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    doc.text(value, 70, y);
    y += 8;
  });

  // Timeline
  y += 5;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 43, 70);
  doc.text("Academic Timeline", 20, y);
  y += 10;

  // Table headers
  doc.setFillColor(240, 243, 246);
  doc.rect(20, y - 5, 170, 8, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80, 80, 80);
  doc.text("Level", 22, y);
  doc.text("Institution", 55, y);
  doc.text("Period", 120, y);
  doc.text("Status", 160, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  learner.timeline.forEach((entry) => {
    doc.text(entry.level, 22, y);
    doc.text(entry.institution, 55, y);
    doc.text(entry.period, 120, y);

    if (entry.status === "Verified") {
      doc.setTextColor(31, 122, 92); // verified green
    } else {
      doc.setTextColor(120, 120, 120);
    }
    doc.text(entry.status, 160, y);
    doc.setTextColor(30, 30, 30);

    if (entry.result) {
      y += 5;
      doc.setFontSize(7);
      doc.setTextColor(100, 100, 100);
      doc.text(`Result: ${entry.result}`, 55, y);
      doc.setFontSize(8);
      doc.setTextColor(30, 30, 30);
    }

    y += 8;
  });

  // Footer line
  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, 190, y);
  y += 8;

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("This report was generated by EduTrack Uganda.", 20, y);
  y += 5;
  doc.text(`Verify this report: ${verifyUrl}`, 20, y);
  y += 5;
  doc.text(`Generated on: ${new Date().toLocaleDateString("en-UG", { year: "numeric", month: "long", day: "numeric" })}`, 20, y);
  y += 5;
  doc.text("Sensitive documents (UNEB result slips, transcripts) are not included in this report.", 20, y);

  // Bottom QR
  doc.addImage(qrDataUrl, "PNG", 80, y + 5, 50, 50);
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("Scan to verify authenticity", 88, y + 58);

  doc.save(`EduTrack_Report_${learner.id}.pdf`);
}

export async function generateQRCodeDataUrl(edutrackId: string, baseUrl: string): Promise<string> {
  const verifyHash = btoa(edutrackId).replace(/[^a-zA-Z0-9]/g, "").slice(0, 16);
  const verifyUrl = `${baseUrl}/verify/${verifyHash}`;
  return QRCode.toDataURL(verifyUrl, {
    width: 200,
    margin: 2,
    color: { dark: "#0F2B46", light: "#FFFFFF" },
  });
}
